export const products = [
  {
    id: 1,
    name: "Galleta redonda con mermelada de durazno",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 2000,
    shape: "Redonda",
    flavor: "Durazno",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Durazno",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1FfBf7S80n8a-XiLs4aojCNSKdtIpzZBn",
  },
  {
    id: 2,
    name: "Galleta corazón con mermelada de durazno",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 2000,
    shape: "Corazón",
    flavor: "Durazno",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Durazno",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1T055RythP5MrhV_bBmXs1V6Hw7pO7ElO",
  },
  {
    id: 3,
    name: "Galleta corazón con mermelada de mora",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 2000,
    shape: "Corazón",
    flavor: "Mora",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Mora",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1pugSXgzR9jUH6fMNrv3sNyTueAXD8o3n",
  },
  {
    id: 4,
    name: "Galleta corazón tradicional",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 1500,
    shape: "Corazón",
    flavor: "Natural",
    servings: 1,
    measurements: {
      length: 7.5,
      width: 7,
      height: 0.5,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1ACUwfca_V276qWZRwUqLkYuyAzg__Yjx",
  },
  {
    id: 5,
    name: "Galleta redonda tradicional",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas tradicionales",
    price: 1500,
    shape: "Redonda",
    flavor: "Natural",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 0.5,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1IfRbVP0FJNnIXXJtm0Yc2uev-N04Str_",
  },
  {
    id: 6,
    name: "Galleta redonda con mermelada de mora",
    category: "Galletas de mantequilla",
    type: "Galleta",
    subcategory: "Galletas con mermelada",
    price: 2000,
    shape: "Redonda",
    flavor: "Mora",
    servings: 1,
    measurements: {
      length: 6,
      width: 6,
      height: 1,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Huevo",
      "Extracto de vainilla",
      "Azúcar pulverizada",
      "Mora",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1crE833FWcqEW7dwcj7fCzg0JLAZ0tYJo",
  },
  {
    id: 7,
    name: "Muffin grande de banano",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 4000,
    shape: "Tradicional",
    flavor: "Banano",
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1fBU_ukGbIN3oPnpykb_SEkl2m2B1Mcb-",
  },
  {
    id: 8,
    name: "Muffin pequeño de banano",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 2000,
    shape: "Tradicional",
    flavor: "Banano",
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Pequeño",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1lgc2HfoFxcp8-MQzGd-n8p08UAI-nSUk",
  },
  {
    id: 9,
    name: "Muffin pequeño de banano con nueces",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 2500,
    shape: "Tradicional",
    flavor: ["Banano", "Nuez"],
    servings: 1,
    measurements: {
      length: 7,
      width: 7,
      height: 4,
    },
    size: "Pequeño",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Nueces",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1-Gocn-zJeIIyrd34Z2pxy9eOWYIvr2I7",
  },
  {
    id: 10,
    name: "Muffin grande de banano con nueces",
    category: "Muffins y panes de banano",
    type: "Muffin",
    subcategory: "Muffins de banano",
    price: 4500,
    shape: "Tradicional",
    flavor: ["Banano", "Nuez"],
    servings: 1,
    measurements: {
      length: 9,
      width: 9,
      height: 6,
    },
    size: "Grande",
    quantity: "Individual",
    ingredients: [
      "Harina",
      "Azúcar",
      "Mantequilla",
      "Banano",
      "Nueces",
      "Huevo",
      "Polvo de hornear",
      "Canela",
      "Sal",
      "Aceite vgetal",
      "Extracto de vainilla",
    ],
    image:
      "https://drive.google.com/uc?export=view&id=1EuSlEdna9KOxwh8HcVgPaBhjLgk2F899",
  },
];

export const categories = [
  {
    id: "c1",
    name: "Galletas de mantequilla",
    url: "https://drive.google.com/uc?export=view&id=1NoZ7idFQgKOxGm-EB2U-2aT9CKBUtNqX",
  },
  {
    id: "c2",
    name: "Muffins y panes de banano",
    url: "https://drive.google.com/uc?export=view&id=1vnSW6OS35GhHTKoktHgGT7DBcOLzJzXD",
  },
];
